/*
 Copyright (c) 2013 yvt

 This file is part of OpenSpades.

 OpenSpades is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OpenSpades is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with OpenSpades.  If not, see <http://www.gnu.org/licenses/>.

 */

#version 450

layout(location = 0) in vec4 texCoord1;
layout(location = 1) in vec4 texCoord2;

layout(location = 0) out vec4 outColor;

layout(binding = 0) uniform sampler2D mainTexture;

void main() {
	// generated by ./1dgaussGen.rb
	// pixelShift is texture coord shift / texture pixel
	const float scale1 = 0.178704407070903;
	const float scale2 = 0.321295592929097;
	const float scale3 = 0.321295592929097;
	const float scale4 = 0.178704407070903;

	outColor = texture(mainTexture, texCoord1.xy) * scale1;
	outColor += texture(mainTexture, texCoord1.zw) * scale2;
	outColor += texture(mainTexture, texCoord2.xy) * scale3;
	outColor += texture(mainTexture, texCoord2.zw) * scale4;
}
